apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: 
AgA57WDPFKbZ/uPXykc4/jD9nF0DiFSAGegyOFenHtNim+VYC2/WeTASBEyZ/+4UQPf9oRjFbNFsGcN+oYEstGAmnsgWzJKERj/JPCMP0dErg7xuXXtvfdLt6UurSnohqPePy/N3oUO7op1Ulm02PIR5O5+pHyyHm6RYt5ltjzDA9BZqLl+QMu1YdYENFE78cx4U0/CYx35SXqNGkaYzWMRe0obCek5OQ2ldZ6YO80zv1nbOZfXUi/b7sN2H/zvgbLuyDkiv48yJ1CqsM0cjTs5tIKDMZPTOStFC8NwP4gnkXaOcEJRP0Yh/ZR9/dp162sM145ZiRJXBvKlyQDKnVDVp564qBiIPdTUMolCHzN4Nst6SOW9vHs6J9hqlf+MnvWCpwMV5zw6xd9miSaJ160HoRzQJMWbd+EThlbxrpe4rHwW15VqtX5JUYeVKbSw88lX0a6dqVofqkteQHDSv7ZpIGfYxZj0aCsdcSSMoO3fbaJ587KqU9k6nqyzll/3cVANBVVnRY1xBHjwRq/UXW5evVDb4Bsloo624aFf10NXmIZ+YHOb1DuXJZx+3blo+j2xrYe8NFBVPzpPKH6/q+aSn2H471JBNPzscqCCu+/p6Lq5P1qg85SIdiYsMyjdy4hDrzbxbqLZzW2XAlpjyb6/9iJZAPFkn6L67r27jDUXWh9s2Gj3ToEm0dVAJKdp0pFwJSCCO0dfIhhGf/Rzs
    root-user: 
AgARp/QVXkQYubKm9hlkTExTawfeMojTv3G4w/+MsJZ+CXz11mxeKScpQGBuX3Z8o5PNu1KUfRKZTRD+efF+IHg+HINdrU0FqwCkPAYgaBCcmmGxnPIoj/Yqsdw5XKbD8tsVlNIHYPSId2qodYSER/wBgk/anX8OVSMx0PfB6JwLlapiT4s+icGbfhmhSvPoSRhwqx+A6GeQ1+8NIosdhNXv64pU0jIAbxjLGFdVNHoubo9O1WoJoctQKnbmt2E8hDdlM4fJWeHAvrSK2hMNpfIm9xfCCprOfySpwItGk5L/c3JT3QqvsVMaGS1QfS1jAqYunht5PyvrisufvvD5q7H1dchJro5YMreeitiKtnm7aFoeDaJ9/jLkbPjRcl8CT02AkTTNPEWSWBFapkvRGjL+upJLIKaLzhyapT6gOFrxVCQ9l3zBYKKYw+a8OHUQJ28FlgOIDbBujQ5/JUe5lUSS5Z7ZLefPb9TslsoLp6lABJLc0HJ+1LFtzyUilxex1GUkXSYMy5zCGZz8cQFLBqaMkAkaBnwBdoePBsehAS0RxrFfp3u5XH8gRQ0Wm0ybpuqE+TlDi1jKbZUqxon+0QDGhbruKIgRH4bri6B1l4OQNgQJEa8EklSrfPrsQ2/SziyaQDOBygJGPZhdSGNtUr0lPQsURASuVI3Y7Ijw7613b8GF95XxIcFDGAo+wU+5guqA1g0+rg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
